services:
  producer:
    container_name: producer
    build: ./producer
    develop:
      watch:
        - action: sync+restart
          path: ./producer
          target: /usr/src/app
    depends_on:
      - mq
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./usr/src/app/node_modules
  consumer:
    container_name: consumer
    build: ./consumer
    develop:
      watch:
        - action: sync+restart
          path: ./consumer
          target: /usr/src/app
    depends_on:
      - mq
    tty: true
    volumes:
      - ./usr/src/app/node_modules
  mq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
