services:
  producer:
    container_name: producer
    build: ./producer
    depends_on:
      - mq
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./producer:/usr/src/app
      - ./usr/src/app/node_modules
  consumer:
    container_name: consumer
    build: ./consumer
    depends_on:
      - mq
    tty: true
    volumes:
      - ./consumer:/usr/src/app
      - ./usr/src/app/node_modules
  mq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
