version: '3'
services:
  app:
    container_name: rest
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./:/usr/src/app
      - ./usr/src/app/node_modules
  db:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
