version: '3'
services:
  app:
    container_name: node-redis
    build: .
    depends_on:
      - cache
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./:/usr/src/app
      - ./usr/src/app/node_modules
  cache:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
